
package Interfaz;

import Dominio.*;
import java.util.*;
import javax.swing.JOptionPane;

public class VentanaCompra extends javax.swing.JFrame {

    public VentanaCompra(Mercado unMercado) {
        mercado = unMercado;
        initComponents();
        this.setSize(1000,1000);
        productosAComprar = new HashMap<>();
        lstPuestos.setListData(mercado.getListaPuestos().toArray());
        lstMayoristas.setListData(mercado.getListaMayoristas().toArray());
        txtCantidad.setText("0");
        txtPrecioUnitario.setText("0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPuestos = new javax.swing.JList();
        lblCompra = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMayoristas = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstProductosOfrecidos = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstProductosAComprar = new javax.swing.JList();
        txtCantidad = new javax.swing.JTextField();
        txtPrecioUnitario = new javax.swing.JTextField();
        txtPrecioTotal = new javax.swing.JTextField();
        btnComprar = new javax.swing.JButton();
        btnAgregarProducto = new javax.swing.JButton();
        btnQuitarProducto = new javax.swing.JButton();
        lblPuestos = new javax.swing.JLabel();
        lblMayoristas = new javax.swing.JLabel();
        lblOfertaProductos = new javax.swing.JLabel();
        lblProductosSeleccionados = new javax.swing.JLabel();
        lblCantComprar = new javax.swing.JLabel();
        lblPrecioUnitario = new javax.swing.JLabel();
        lblPrecioTotal = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstProductosAComprarCantidad = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lstPuestos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstPuestos);

        lblCompra.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCompra.setText("Registro de Compras");

        lstMayoristas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstMayoristas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstMayoristasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstMayoristas);

        lstProductosOfrecidos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(lstProductosOfrecidos);

        lstProductosAComprar.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstProductosAComprar.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstProductosAComprarValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstProductosAComprar);

        txtPrecioTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioTotalActionPerformed(evt);
            }
        });

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnAgregarProducto.setText("->");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        btnQuitarProducto.setText("<-");
        btnQuitarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarProductoActionPerformed(evt);
            }
        });

        lblPuestos.setText("Puestos");

        lblMayoristas.setText("Mayoristas");

        lblOfertaProductos.setText("Oferta");

        lblProductosSeleccionados.setText("A Comprar");

        lblCantComprar.setText("Seleccione la cantidad a comprar:");

        lblPrecioUnitario.setText("Seleccione el precio unitario:");

        lblPrecioTotal.setText("Precio Total");

        lstProductosAComprarCantidad.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstProductosAComprarCantidad.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstProductosAComprarCantidadValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(lstProductosAComprarCantidad);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(lblCompra))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblPrecioUnitario)
                                        .addGap(37, 37, 37))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCantComprar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrecioUnitario)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(lblPuestos, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                .addGap(117, 117, 117)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblMayoristas, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblOfertaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnQuitarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblProductosSeleccionados, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblPrecioTotal)
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnComprar)
                                            .addComponent(txtPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMayoristas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblOfertaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblProductosSeleccionados, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarProducto)
                                .addGap(33, 33, 33)
                                .addComponent(btnQuitarProducto)))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantComprar))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecioUnitario)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPrecioTotal))))))
                .addGap(209, 209, 209))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 850, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        
        
    }//GEN-LAST:event_btnComprarActionPerformed

    private void lstMayoristasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMayoristasValueChanged
        Mayorista mayoristaSeleccionado = (Mayorista) lstMayoristas.getSelectedValue();
        System.out.println(mayoristaSeleccionado);
        int posicion = mercado.getListaMayoristas().indexOf(mayoristaSeleccionado);
        System.out.println(posicion);
        lstProductosOfrecidos.setListData(mercado.getListaMayoristas().get(posicion).getProducto().toArray());
        
    }//GEN-LAST:event_lstMayoristasValueChanged

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        String mensajeError = "";
        boolean hayCantidad = true;
        boolean hayPrecio = true;
        
        if(txtCantidad.getText().equals("0")){
            mensajeError += "Seleccione una cantidad\n";
            hayCantidad = false;
        }else if(!txtCantidad.getText().matches("\\d+[.,]?\\d*")){
            mensajeError += "Seleccione una cantidad en formato numerico\n";
        }
        if(txtPrecioUnitario.getText().equals("0")){
            mensajeError += "Seleccione un precio por unidad\n";
            hayPrecio = false;
        }else if(!txtPrecioUnitario.getText().matches("\\d+[.,]?\\d*")){
            mensajeError += "Seleccione una cantidad en formato numerico\n";
            hayPrecio = false;
        }
        
        
        if(!lstProductosOfrecidos.isSelectionEmpty() && hayCantidad && hayPrecio){
            float[] cantYPrecio = {Float.parseFloat(txtCantidad.getText()),Float.parseFloat(txtPrecioUnitario.getText())};
            productosAComprar.put((Producto)lstProductosOfrecidos.getSelectedValue(), cantYPrecio);
            //lstProductosAComprar.setListData(productosAComprar.keySet().toArray());
            //lstProductosAComprarCantidad.setListData(productosAComprar.values().toArray());            
            
        } else{
            JOptionPane.showMessageDialog(this, mensajeError, "Faltan algunos Datos", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void lstProductosAComprarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstProductosAComprarValueChanged
        if (!evt.getValueIsAdjusting()) {
            int posicionSeleccionada = lstProductosAComprar.getSelectedIndex();
            lstProductosAComprarCantidad.setSelectedIndex(posicionSeleccionada);
        }
    }//GEN-LAST:event_lstProductosAComprarValueChanged

    private void lstProductosAComprarCantidadValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstProductosAComprarCantidadValueChanged
        if (!evt.getValueIsAdjusting()) {
            int posicionSeleccionada = lstProductosAComprarCantidad.getSelectedIndex();
            lstProductosAComprar.setSelectedIndex(posicionSeleccionada);
        }
    }//GEN-LAST:event_lstProductosAComprarCantidadValueChanged

    private void btnQuitarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarProductoActionPerformed
        String mensajeError = "";
        if(!lstProductosAComprar.isSelectionEmpty()){
            productosAComprar.remove((Producto)lstProductosAComprar.getSelectedValue());
            lstProductosAComprar.setListData(productosAComprar.keySet().toArray());
            lstProductosAComprarCantidad.setListData(productosAComprar.values().toArray());
            
        } else{
            JOptionPane.showMessageDialog(this, mensajeError, "Por favor, seleccione un producto de su carrito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnQuitarProductoActionPerformed

    private void txtPrecioTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioTotalActionPerformed
        float cant = Float.parseFloat(txtCantidad.getText());
        float pUnit = Float.parseFloat(txtPrecioUnitario.getText());
        float pTotal = cant * pUnit;
        
        txtPrecioTotal.setText("" + pTotal);
    }//GEN-LAST:event_txtPrecioTotalActionPerformed

    private void reCargar(){
        this.lstPuestos.setListData(mercado.getListaPuestos().toArray());
        this.lstMayoristas.setListData(mercado.getListaMayoristas().toArray());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnQuitarProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCantComprar;
    private javax.swing.JLabel lblCompra;
    private javax.swing.JLabel lblMayoristas;
    private javax.swing.JLabel lblOfertaProductos;
    private javax.swing.JLabel lblPrecioTotal;
    private javax.swing.JLabel lblPrecioUnitario;
    private javax.swing.JLabel lblProductosSeleccionados;
    private javax.swing.JLabel lblPuestos;
    private javax.swing.JList lstMayoristas;
    private javax.swing.JList lstProductosAComprar;
    private javax.swing.JList lstProductosAComprarCantidad;
    private javax.swing.JList lstProductosOfrecidos;
    private javax.swing.JList lstPuestos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtPrecioTotal;
    private javax.swing.JTextField txtPrecioUnitario;
    // End of variables declaration//GEN-END:variables
    private Mercado mercado;
    private HashMap<Producto, float[]> productosAComprar;
}
